Add regression tests for X-Accel-Buffering passing
dcos/adminrouter pull request #54
Opened 2017-02-27 16:55 UTC by mhrabovcin

Fixes [DCOS-14147](https://jira.mesosphere.com/browse/DCOS-14147). I'll move patch to `dcos/dcos` once https://github.com/dcos/dcos/pull/1291/files gets merged.

2017-02-27 21:03 UTC, vespian requested changes
Left some comments.

We will also have create a EE PR for https://jira.mesosphere.com/browse/DCOS-14193 / https://github.com/mesosphere/adminrouter/pull/134 related tests.

2017-02-27 21:03 UTC, vespian commented on test-harness/modules/generic_test_code.py
> +        headers (array): additional headers to test in format (name, value)
Why `(name, value)` instead of a dict?

Using dictionary makes us not have to worry about user supplying multiple values for a single header.

2017-02-27 21:03 UTC, vespian commented on test-harness/modules/generic_test_code.py
> +    expected_host = "127.0.0.1" if ar.role == "master" else "127.0.0.1:61001"
This one is tricky, I would very much like us to skip it.

This can be `leader.mesos` or `master.mesos` or anything really, depending on how the `location` block is configured. Now that we have `assert_headers` I would rather leave this to user to decide.

2017-02-27 21:03 UTC, vespian commented on test-harness/tests/test_agent.py
> +                              ("/system/v1/logs/v1/", "/"),
can I have here also `/system/v1/logs/v1` path please?

2017-02-28 09:16 UTC, mhrabovcin commented on test-harness/tests/test_agent.py
> +                              ("/system/v1/logs/v1/", "/"),
This is a copy&paste from `test_master.py` which doesn't test `/system/v1/logs/v1` because there is a redirect to `/system/v1/logs/v1/`.

2017-02-28 10:45 UTC, vespian commented on test-harness/tests/test_agent.py
> +                              ("/system/v1/logs/v1/", "/"),
ah, I missed it,

2017-02-28 20:22 UTC, gpaul approved these changes
:ship:

2017-03-02 10:03 UTC, mhrabovcin commented
Closing in favour of https://github.com/dcos/dcos/pull/1312

2017-03-02 10:03 UTC, closed without merging